##!/bin/bash
##PBS -l walltime=53:00
#PBS-j oe
#PBS -N bomba_NAS1
##PBS -lnodes=4:ppn=2
cat $PBS_NODEFILE


#module add gnu/4.9.0

cd ~/NPB3.3.1/tests/

#gcc 4.4.6

for gccver in "4.4.6" "4.9.0"
do

cd "gcc/$gccver"

echo "------------- gcc -> $gccver -----------"

cd SER
./script_SER.sh
cd ..

cd MPI
./script_MPI.sh
cd ..

cd OMP
./script_OMP.sh
cd ..

cd ../..
done



#gcc -v
#cat /proc/cpuinfo

